name: "Flatpak External Data Checker"
author: "The Flatpak External Data Checker authors"
description: "A tool for checking if the external data used in Flatpak manifests is still up to date" 
inputs:
  # todo these are untrusted inputs, so ensure we handle safely
  # even though this action might only run in an individual repo, it still has some amount of access (at least by default)
  # so at bare minimum this should do some sanity checks on the inputs somehow
  manifest_path:
    description: "Exact path to the Flatpak manifest in your GitHub repo."
    required: true
  name_input:
    description: "Name of user to do commits"
    required: true
    default: Flatpak External Data Checker
  email_input:
    description: "Email of user to do commits"
    required: true
    default: ${{ github.actor }}
  require_important_update:
    description: "Require an update to a main or important source before updating the manifest."
    required: false
    default: "false"
  automerge_fedc_prs:
    description: "Automerge f-e-d-c PRs that pass CI. Todo this needs integration and renaming."
    required: false
    default: "false"

runs:
  using: "docker"
  image: "Dockerfile" # can we include parallel in upstream image and mount the script instead?
  
  env: 
    MANIFEST_PATH: ${{ inputs.manifest_path }}
    GIT_AUTHOR_NAME: ${{ inputs.name_input }}
    GIT_AUTHOR_EMAIL: ${{ inputs.email_input }}@users.noreply.github.com
    REQUIRE_IMPORTANT_UPDATE: ${{ inputs.require_important_update }} # verify these actually work, docs seem to specify this they need be args, but maybe env can be used instead
    AUTOMERGE_FEDC_PRS: ${{ inputs.automerge_fedc_prs }}
    
    # todo, I believe there is a way of restricting an action's permissions, if possible that would make a lot of sense.
    